platformd:
  token:
    secret: "24n$#%oeoe843%5eo,ntour4/"
  google:
    clientId: "714940765820-4ronadar6r8rjgkn0lih986sgi14vl0o.apps.googleusercontent.com"

server:
  port: 8443
  ssl:
    key-store: config/platformd.p12
    key-store-password: Screw you! Add via command line/ in a properties file in the folder config
    keyStoreType: PKCS12
    keyAlias: platformd.se